Models/ViewModels/Shared/ErrorViewModel.cs
namespace Tickest.Models.ViewModels.Shared
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EspecialidadeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tickest.Data;
using Tickest.Models.Entities;
using Tickest.Models.ViewModels;


namespace Tickest.Controllers
{
    [Authorize(Roles = "Gerenciador")]
    public class EspecialidadeController : Controller
    {
        private readonly UserManager<Usuario> userManager;
        private readonly TickestContext _context;

        public EspecialidadeController(UserManager<Usuario> userManager, TickestContext context)
        {
            this.userManager = userManager;
            _context = context;
        }

        public IActionResult Create()
        {
            var query = _context.Departamentos
                .AsQueryable();

            var viewModel = new UsuarioViewModel()
            {
                Departamentos = query.Select(p => new Departamento
                {
                    Id = p.Id,
                    Nome = p.Nome,
                    GerenciadorId = p.GerenciadorId,
                    Usuarios = p.Usuarios,
                    Especialidades = p.Especialidades
                }).ToList()
            };

            return View(viewModel);
        }

        // POST: EspecialidadeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,DepartamentoId")] Especialidade Especialidade)
        {
            _context.Add(Especialidade);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Gerenciador");
        }

        [HttpGet]
        public async Task<IActionResult> ObterEspecialidadesPorDepartamento(int departamentoId)
        {
            if (departamentoId == 0)
                return Json(new List<EspecialidadeViewModel>());

            var especialidades = await _context.Especialidades
                .Where(p => p.DepartamentoId == departamentoId)
                .Select(p => new EspecialidadeViewModel
                {
                    Id = p.Id,
                    Nome = p.Nome
                }).ToListAsync();

            return Json(especialidades);
        }
    }
}

Controllers/NotificacoesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Tickest.Controllers
{
    public class NotificacoesController : Controller
    {
        // GET: NotificacoesController
        public ActionResult Index()
        {
            return View();
        }

        // GET: NotificacoesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: NotificacoesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NotificacoesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NotificacoesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NotificacoesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NotificacoesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NotificacoesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/ResponsaveisController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using Tickest.Data;
using Tickest.Enums;
using Tickest.Models.Entities;
using Tickest.Models.ViewModels;


namespace Tickest.Controllers
{
    [Authorize(Roles = "Gerenciador, Responsavel")]
    public class ResponsaveisController : Controller
    {
        private readonly UserManager<Usuario> _userManager;
        private readonly TickestContext _context;

        public ResponsaveisController(UserManager<Usuario> userManager, TickestContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Index()
        {
            var usuario = _userManager.FindByEmailAsync(User.Identity.Name).Result;

            var tickets = _context.Tickets
                .Include(t => t.Departamento)
                .Include(t => t.Responsavel)
                .Include(t => t.Anexos)
                .Where(t => t.EspecialidadeId == usuario.EspecialidadeId &&
                            (t.Status != TicketStatusEnum.Concluido && t.Status != TicketStatusEnum.Cancelado))
                .ToList();

            tickets.RemoveAll(t => t.Status != TicketStatusEnum.Aberto && t.SolicitanteId != usuario.Id);

            var viewModel = new TicketViewModel
            {
                Tickets = tickets,
                Usuario = usuario
            };

            PopulateTicketCounts(viewModel, usuario);

            return View(viewModel);
        }

        public IActionResult Departamento()
        {
            var usuario = _userManager.FindByEmailAsync(User.Identity.Name).Result;

            var tickets = _context.Tickets
                .Include(t => t.Departamento)
                .Include(t => t.Responsavel)
                .Include(t => t.Anexos)
                .Where(t => t.DepartamentoId == usuario.DepartamentoId)
                .ToList();

            var viewModel = new TicketViewModel
            {
                Tickets = tickets,
                Usuario = usuario
            };

            return View(viewModel);
        }

        private void PopulateTicketCounts(TicketViewModel viewModel, Usuario usuario)
        {
            viewModel.TicketsRecebidos = _context.Tickets
                .Count(t => t.SolicitanteId == usuario.Id &&
                            (t.Status != TicketStatusEnum.Cancelado && t.DataCriacao.Month == DateTime.Now.Month)).ToString();

            viewModel.TicketConcluidos = _context.Tickets
                .Count(t => t.SolicitanteId == usuario.Id &&
                            (t.Status == TicketStatusEnum.Concluido && t.DataStatus.Month == DateTime.Now.Month)).ToString();

            viewModel.TicketsAbertos = _context.Tickets
                .Count(t => t.SolicitanteId == usuario.Id && t.Status == TicketStatusEnum.Aberto).ToString();
        }

    }

}

Controllers/TicketsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Tickest.Data;
using Tickest.Models.Entities;
using Tickest.Enums;
using Tickest.Helpers;
using Microsoft.EntityFrameworkCore;
using Tickest.Models.ViewModels;


namespace Tickest.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly UserManager<Usuario> _userManager;
        private readonly TickestContext _context;
        private readonly ILogger<TicketsController> _logger;

        public TicketsController(UserManager<Usuario> userManager, TickestContext context, ILogger<TicketsController> logger)
        {
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<IActionResult> Index()
        {
            var usuarioAtual = await _userManager.GetUserAsync(User);

            var tickets = await _context.Tickets
                .Include(t => t.Departamento)
                .Include(t => t.Responsavel)
                .Include(t => t.Anexos)
                .Include(t => t.Solicitante)
                .Where(t => t.SolicitanteId == usuarioAtual.Id)
                .Where(t => t.Status != TicketStatusEnum.Concluido && t.Status != TicketStatusEnum.Cancelado)
                .OrderBy(t => t.Id)
                .ToListAsync();

            var viewModel = new TicketViewModel
            {
                Tickets = tickets,
                Usuario = usuarioAtual
            };

            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Gerenciador,Analista,Cliente")]
        public async Task<IActionResult> Historic()
        {
            var usuarioAtual = await _userManager.GetUserAsync(User);
            var userRole = (await _userManager.GetRolesAsync(usuarioAtual)).FirstOrDefault();

            IQueryable<Ticket> query = _context.Tickets
                .Include(t => t.Departamento)
                .Include(t => t.Responsavel)
                .Include(t => t.Solicitante)
                .Include(t => t.Anexos);

            if (userRole == "Gerenciador")
            {
                // Gerenciador: Ver todos os tickets concluídos ou cancelados
                query = query.Where(t => t.Status == TicketStatusEnum.Concluido || t.Status == TicketStatusEnum.Cancelado);
            }
            else if (userRole == "Analista")
            {
                // Analista: Ver todos os tickets que ele é responsável e estão concluídos ou cancelados
                query = query.Where(t => t.Responsavel.Email == usuarioAtual.Email &&
                                          (t.Status == TicketStatusEnum.Concluido || t.Status == TicketStatusEnum.Cancelado));
            }
            else if (userRole == "Cliente")
            {
                // Cliente: Ver todos os tickets que ele solicitou e estão concluídos ou cancelados
                query = query.Where(t => t.SolicitanteId == usuarioAtual.Id &&
                                          (t.Status == TicketStatusEnum.Concluido || t.Status == TicketStatusEnum.Cancelado));
            }

            var tickets = await query.OrderBy(t => t.Id).ToListAsync();

            var viewModel = new TicketViewModel
            {
                Tickets = tickets,
                Usuario = usuarioAtual
            };

            return View(viewModel);
        }




        public async Task<IActionResult> Search(string search)
        {
            var usuario = await _userManager.GetUserAsync(User);

            var tickets = await _context.Tickets
                .Include(t => t.Departamento)
                .Include(t => t.Responsavel)
                .Include(t => t.Anexos)
                .Where(t => t.Responsavel.Email == usuario.Email
                    && (EF.Functions.Like(t.Titulo, $"%{search}%")
                    || t.Id.ToString() == search
                    || EF.Functions.Like(t.Descricao, $"%{search}%")
                    || EF.Functions.Like(t.Departamento.Nome, $"%{search}%")))
                .OrderBy(t => t.Id)
                .ToListAsync();

            var viewModel = new TicketViewModel
            {
                Tickets = tickets,
                Usuario = usuario
            };

            ViewBag.Titulo = $"Pesquisando por {search}";

            return View(viewModel);
        }

        //public async Task<IActionResult> Create()
        //{
        //    var user = await _userManager.GetUserAsync(User);

        //    var departamentos = await _context.Departamentos
        //        .OrderBy(d => d.Nome)
        //        .ToListAsync();

        //    var especialidades = await _context.Especialidades
        //        .OrderBy(e => e.Nome)
        //        .ToListAsync();

        //    var viewModel = new TicketViewModel
        //    {
        //        Departamentos = departamentos,
        //        Especialidades = especialidades
        //    };

        //    return View(viewModel);
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(TicketViewModel viewModel, List<IFormFile> files)
        //{
        //    var usuario = await _userManager.GetUserAsync(User);

        //    if (usuario == null)
        //    {
        //        return NotFound("Usuário não encontrado.");
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        var ticket = viewModel.Ticket;
        //        var departamentoId = viewModel.Ticket.DepartamentoId;

        //        // Verifica se o departamentoId existe na base de dados
        //        var departamentoExistente = await _context.Departamentos.FindAsync(departamentoId);
        //        if (departamentoExistente == null)
        //        {
        //            ModelState.AddModelError(nameof(Ticket.DepartamentoId), "Departamento não encontrado.");
        //            // Recarrega as listas de departamentos e especialidades para exibir no formulário
        //            viewModel.Departamentos = await _context.Departamentos.OrderBy(d => d.Nome).ToListAsync();
        //            viewModel.Especialidades = await _context.Especialidades.OrderBy(e => e.Nome).ToListAsync();
        //            return View(viewModel);
        //        }

        //        // Processa os anexos
        //        if (files != null && files.Count > 0)
        //        {
        //            foreach (var file in files)
        //            {
        //                var path = await WriteFileAsync(file);
        //                var fileName = Path.GetFileName(path);
        //                var name = "anexos/" + fileName;
        //                var anexo = new Anexo { Endereco = name };
        //                ticket.Anexos.Add(anexo);
        //            }
        //        }

        //        // Configuração dos campos do ticket
        //        ticket.DataCriacao = DateTime.Now;
        //        ticket.Status = TicketStatusEnum.Aberto;
        //        ticket.DataStatus = DateTime.Now;
        //        ticket.SolicitanteId = usuario.Id;

        //        _context.Add(ticket);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }

        //    // Se o modelo não for válido, recarrega as listas de departamentos e especialidades para exibir no formulário
        //    viewModel.Departamentos = await _context.Departamentos.OrderBy(d => d.Nome).ToListAsync();
        //    viewModel.Especialidades = await _context.Especialidades.OrderBy(e => e.Nome).ToListAsync();
        //    return View(viewModel);
        //}

        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound("Usuário não encontrado.");
            }

            var departamentos = await _context.Departamentos
                .OrderBy(d => d.Nome)
                .ToListAsync();

            var especialidades = await _context.Especialidades
                .OrderBy(e => e.Nome)
                .ToListAsync();

            var viewModel = new TicketViewModel
            {
                Ticket = new Ticket(), // Inicializa um novo Ticket
                Departamentos = departamentos,
                Especialidades = especialidades
            };

            return View(viewModel);
        }


        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return BadRequest("O ID do ticket não pode ser nulo.");
            }

            var ticket = await _context.Tickets
                .Include(t => t.Departamento)
                .Include(t => t.Solicitante)
                .FirstOrDefaultAsync(t => t.Id == id);

            if (ticket == null)
            {
                return NotFound();
            }

            var viewModel = new TicketViewModel
            {
                Ticket = ticket,
                Departamentos = await _context.Departamentos.OrderBy(d => d.Nome).ToListAsync(),
                Especialidades = await _context.Especialidades.OrderBy(e => e.Nome).ToListAsync()
            };

            return View("~/Views/Gerenciador/AllTickets.cshtml", viewModel);

Views/Shared/_LayoutCliente.cshtml
@inject Tickest.Data.TickestContext _context

@{
    var Usuario = _context.Usuarios
        .FirstOrDefault(p => p.Email == User.Identity.Name); 
}

<!DOCTYPE html>

<html lang="pt-br" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-template="vertical-menu-template-free">

<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <meta name="description" content="" />

    <title>Tickest</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/img/logo/Logo2.png" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/css/demo.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
    <link rel="stylesheet" href="~/vendor/libs/apex-charts/apex-charts.css" />

    <!-- DataTable -->
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.css" rel="stylesheet">

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="~/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="~/js/config.js"></script>
</head>

<body>

    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">

            <!-- Menu -->
            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
                <div class="app-brand demo">
                    <!-- Logo -->
                    <div class="app-brand justify-content-center">
                        <a class="app-brand-link gap-2">
                            <span class="app-brand-logo demo">
                                <img src="~/img/logo/Logo.png" alt="" style="width:15%">
                            </span>
                        </a>
                    </div>
                    <!-- /Logo -->
                </div>

                <div class="menu-inner-shadow"></div>

                <ul class="menu-inner py-1">

                    <li class="menu-header small text-uppercase">
                        <span class="menu-header-text">Pessoal</span>
                    </li>

                    <li class="menu-item">
                        <a asp-area="" asp-controller="Tickets" asp-action="Index" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-dock-top"></i>
                            <div data-i18n="Account Settings">Tickets Criados</div>
                        </a>
                    </li>

                    <li class="menu-item">
                        <a asp-area="" asp-controller="Tickets" asp-action="Historic" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-history"></i>
                            <div data-i18n="Basic">Histórico de Tickets</div>
                        </a>
                    </li>

                    <li class="menu-header small text-uppercase">
                        <span class="menu-header-text">Ações</span>
                    </li>

                    <li class="menu-item">
                        <a asp-area="" asp-action="Create" asp-controller="Tickets" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-add-to-queue"></i>
                            <div data-i18n="Basic">Criar Ticket</div>
                        </a>
                    </li>

                    <li class="menu-item">
                        <ul class="menu-sub">
                            <li class="menu-item">
                                <a asp-area="" asp-controller="Account" asp-action="Register" class="menu-link">
                                    <div data-i18n="Basic">Usuário</div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a asp-area="" asp-controller="Departamentos" asp-action="Create" class="menu-link">
                                    <div data-i18n="Basic">Departamento</div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a asp-area="" asp-controller="Especialidade" asp-action="Create" class="menu-link">
                                    <div data-i18n="Basic">Especialidade</div>
                                </a>
                            </li>
                        </ul>
                    </li>

                </ul>
            </aside>
            <!-- Menu -->
            <!-- Layout page -->
            <div class="layout-page">

                <!-- Navbar -->
                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">

                        <!-- Search -->
                        <div class="navbar-nav align-items-center">
                            <div class="nav-item d-flex align-items-center">
                                <i class="bx bx-search fs-4 lh-0"></i>
                                <form method="post" action="/Tickets/Search">
                                    <input name="search" type="text"
                                           class="form-control border-0 shadow-none"
                                           placeholder="Pesquisar..."
                                           aria-label="Perquisar..." />

                                </form>
                            </div>
                        </div>

                        <!-- /Search -->

                        <ul class="navbar-nav flex-row align-items-center ms-auto">

                            <li class="avatar avatar btn rounded-pill btn-icon btn-outline-primary bg-light">
                                <a asp-area="" asp-controller="Notificacoes" asp-action="Index" class="text-dark">
                                    <span class="tf-icons bx bx-bell"></span>
                                </a>
                            </li>

                            <!-- User -->
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                    <div class="avatar">
                                        <img src="~/img/avatars/Perfil.jpg" class="w-px-40 h-auto rounded-circle" />
                                    </div>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li>
                                        <a asp-area="" asp-controller="Usuarios" asp-action="Index" class="dropdown-item">
                                            <div class="d-flex">
                                                <div class="flex-shrink-0 me-3">
                                                    <div class="avatar">
                                                        <img src="~/img/avatars/Perfil.jpg" class="w-px-40 h-auto rounded-circle" />
                                                    </div>
                                                </div>
                                                <div class="flex-grow-1">
                                                    <span class="fw-semibold d-block">@Usuario.Nome</span> 
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="dropdown-divider"></div>
                                    </li>
                                    <li class="nav-item">
                                        <form method="post" asp-controller="Account" asp-action="Logout">
                                            <button class="dropdown-item" type="submit">
                                                <i class="bx bx-power-off me-2"></i>
                                                <span class="align-middle">Sair</span>
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </li>
                            <!-- User -->

                        </ul>
                    </div>
                </nav>
                <!-- Navbar -->

                <div class="content-wrapper">

                    <!-- Content wrapper -->
                    <div class="container-xxl flex-grow-1 container-p-y">

                        <div class="container">
                            <main role="main" class="pb-3">
                                @RenderBody()
                            </main>
                        </div>

                        <div class="content-backdrop fade"></div>
                    </div>
                    <!-- Content wrapper -->

                </div>
            </div>
        </div>
        <!-- Layout page -->
        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>
        <!-- Overlay -->
    </div>
    <!-- Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/vendor/libs/jquery/jquery.js"></script>
    <script src="~/vendor/libs/popper/popper.js"></script>
    <script src="~/vendor/js/bootstrap.js"></script>
    <script src="~/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="~/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <script src="~/vendor/libs/apex-charts/apexcharts.js"></script>

    <!-- DataTable JS -->
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.js"></script>

    <!-- Main JS -->
    <script src="~/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/js/dashboards-analytics.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>