Models/Departamento.cs
using System.ComponentModel.DataAnnotations;

namespace Tickest.Models
{
    public class Departamento
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public required string Nome_Departamento { get; set; }

        public required ICollection<Area> Areas { get; set; }
    }
}

Models/Entities/Departamento.cs
using Microsoft.Identity.Client;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Tickest.Models.Entities
{
    public class Departamento
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string? Nome { get; set; }

        public int GerenciadorId { get; set; }

        public ICollection<Usuario> Usuarios { get; set; }

        public ICollection<Especialidade> Especialidades { get; set; }
    }
}

Models/ViewModels/Departamento/DepartamentoEditViewModel.cs
using System.ComponentModel.DataAnnotations;
using Tickest.Models.ViewModels;

namespace Tickest.Models.ViewModels
{
    public class DepartamentoEditViewModel
    {
        public DepartamentoEditViewModel()
        {
            GerenciadoresDisponiveis = new List<GerenciadorViewModel>();
            AnalistasDisponiveis = new List<AnalistaViewModel>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Gerenciador obrigatório")]
        public int? GerenciadorSelecionado { get; set; }

        //[Required(ErrorMessage = "Analista obrigatório")]
        public int? AnalistaSelecionado { get; set; }

        public ICollection <AnalistaViewModel> AnalistasDisponiveis { get; set; }
        public ICollection<GerenciadorViewModel> GerenciadoresDisponiveis { get; set; }
    }
}

Models/ViewModels/Departamento/DepartamentoListViewModel.cs
using Tickest.Models.ViewModels;

namespace Tickest.Models.ViewModels
{
    public class DepartamentoListViewModel
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public string Gerenciador { get; set; }

        public ICollection<EspecialidadeViewModel> Especialidades { get; set; }
    }
}

Models/ViewModels/DepartamentoViewModel.cs
using Tickest.Models.Entities;

namespace Tickest.Models.ViewModels
{
    public class DepartamentoViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        //public async Task<Departamento> { get; set; }
    }
}

Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tickest.Data;
using Tickest.Models.Entities;
using Tickest.Models.ViewModels;

namespace Tickest.Controllers
{
    [Authorize]
    public class DepartamentosController : Controller
    {
        private readonly UserManager<Usuario> userManager;
        private readonly TickestContext _context;

        public DepartamentosController(UserManager<Usuario> userManager, TickestContext context)
        {
            this.userManager = userManager;
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Gerenciador")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var usersGerenciador = await userManager.GetUsersInRoleAsync("Gerenciador");
            var usersAnalista = await userManager.GetUsersInRoleAsync("Analista");

            var viewModel = new DepartamentoEditViewModel()
            {
                Nome = string.Empty,
                GerenciadorSelecionado = 0,
                GerenciadoresDisponiveis = usersGerenciador.Where(p => p.DepartamentoId == null).Select(p => new GerenciadorViewModel { Id = p.Id, Email = p.Email }).ToList(),
                AnalistaSelecionado = 0,
                AnalistasDisponiveis = usersAnalista.Select(e => new AnalistaViewModel { Id = e.Id, Email = e.Email }).ToList()
            };

            return View(viewModel);
        }

        [Authorize(Roles = "Gerenciador")]
        [HttpPost]
        public async Task<IActionResult> Create(DepartamentoEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            var departamento = new Departamento();
            departamento.Nome = viewModel.Nome;
            departamento.GerenciadorId = viewModel.GerenciadorSelecionado.Value;

            _context.Add(departamento);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(List));
        }

        [Authorize(Roles = "Gerenciador")]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usersGerenciador = await userManager.GetUsersInRoleAsync("Gerenciador");
            var usersAnalistas = await userManager.GetUsersInRoleAsync("Analista");

            var departamento = await _context.Set<Departamento>()
                 .Select(departamento => new DepartamentoEditViewModel
                 {
                     Id = departamento.Id,
                     Nome = departamento.Nome,
                     GerenciadorSelecionado = departamento.GerenciadorId,
                     GerenciadoresDisponiveis = usersGerenciador.Select(responsavel => new GerenciadorViewModel
                     {
                         Id = responsavel.Id,
                         Nome = responsavel.Email
                     }).ToList(),
                     AnalistaSelecionado = 0,
                     AnalistasDisponiveis = usersAnalistas.Select(p => new AnalistaViewModel { Id = p.Id, Email = p.Email }).ToList()
                 })
                 .FirstOrDefaultAsync(p => p.Id == id);

            if (departamento == null)
            {
                return NotFound();
            }

            return View(departamento);
        }

        [Authorize(Roles = "Gerenciador")]
        [HttpPost]
        public async Task<IActionResult> Edit(DepartamentoEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            var departamento = await _context.Set<Departamento>().FirstAsync(p => p.Id == viewModel.Id);
            departamento.Nome = viewModel.Nome;
            departamento.GerenciadorId = viewModel.GerenciadorSelecionado.Value;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(List));
        }

        [Authorize(Roles = "Gerenciador")]
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var departamento = await _context.Departamentos.FirstOrDefaultAsync(p => p.Id == id);

            var ticketsDepartamento = _context.Tickets.Where(p => p.DepartamentoId == id);
            var especialidadeDepartamento = _context.Especialidades.Where(p => p.DepartamentoId == id);
            var usuarioDepartamento = _context.Usuarios.Where(p => p.DepartamentoId == id);

            foreach (var item in ticketsDepartamento)
                item.DepartamentoId = null;

            foreach (var item in especialidadeDepartamento)
                item.DepartamentoId = null;

            foreach (var item in usuarioDepartamento)
                item.DepartamentoId = null;

            _context.Remove(departamento);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(List));
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var departamentos = await _context.Set<Departamento>()
               .Select(departamento => new DepartamentoListViewModel
               {
                   Id = departamento.Id,
                   Nome = departamento.Nome,
                   Gerenciador = _context.Set<Usuario>().First(p => p.Id == departamento.GerenciadorId).Nome
               }).ToListAsync();

            return View(departamentos);
        }

        [HttpGet]
        public async Task<IActionResult> ObterDepartamentos()
        {
            List<DepartamentoListViewModel> departamentos = await _context.Set<Departamento>()
                .Select(departamento => new DepartamentoListViewModel
                {
                    Id = departamento.Id,
                    Nome = departamento.Nome,
                    Gerenciador = _context.Set<Usuario>().First(p => p.Id == departamento.GerenciadorId).Nome
                }).ToListAsync();

            return Json(departamentos);
        }
    }
}

Views/Departamentos/Create.cshtml
@using Tickest.Models.ViewModels
@model DepartamentoEditViewModel

@{
    Layout = "_LayoutGerenciador";
    ViewData["Title"] = "Tickest - Adicionar Departamento";
}

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">
            <div class="card mb-4">
                <h5 class="card-header">Adicionar Departamento</h5>
                <div class="card-body">
                    <div class="form-group mb-3">
                        <label asp-for="Nome" class="form-label">Nome</label>
                        <input asp-for="Nome" class="form-control" placeholder="Digite o nome" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>

                    <div class="form-group mb-3">
                        <label asp-for="GerenciadorSelecionado" class="form-label">Gerenciador do Departamento</label>
                        <select asp-for="GerenciadorSelecionado" asp-items="@Model.GerenciadoresDisponiveis.Select(p => new SelectListItem(p.Email, p.Id.ToString()))" class="form-control">
                            <option value="">Selecione o Gerenciador</option>
                        </select>
                        <span asp-validation-for="GerenciadorSelecionado" class="text-danger"></span>
                    </div>

                    <div class="form-group mb-3">
                        <label asp-for="AnalistaSelecionado" class="form-label">Analistas do Departamento</label>
                        <select asp-for="AnalistaSelecionado" asp-items="@Model.AnalistasDisponiveis.Select(e => new SelectListItem(e.Email, e.Id.ToString()))" class="form-control">
                            <option value="">Selecione o Analista</option>
                        </select>
                        <span asp-validation-for="AnalistaSelecionado" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary mt-3">Adicionar</button>
                </div>
            </div>
        </form>
    </div>
</div>

Views/Departamentos/Edit.cshtml
@using Tickest.Models.ViewModels
@model DepartamentoEditViewModel

@{
    Layout = "_LayoutGerenciador";
    ViewData["Title"] = "Tickest - Editar Departamento";
}

<div class="container-fluid bg-white py-4">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            @using (Html.BeginForm("Edit", "Departamentos", FormMethod.Post, new { @class = "card mb-4" }))
            {
                <h5 class="card-header">Editar Departamento</h5>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Nome" class="form-label">Nome</label>
                        <input asp-for="Nome" class="form-control mb-3" placeholder="Nome do Departamento" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="GerenciadorSelecionado" class="form-label">Responsável pelo Departamento</label>
                        @Html.DropDownListFor(model => model.GerenciadorSelecionado, new SelectList(Model.GerenciadoresDisponiveis, "Id", "Nome"), "-- Selecione --", new { @class = "form-control mt-2 mb-3" })
                        <span asp-validation-for="GerenciadorSelecionado" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary mt-3">Salvar</button>
                </div>
            }
        </div>
    </div>
</div>

Views/Departamentos/List.cshtml
@using Microsoft.AspNetCore.Identity
@using Tickest.Models.ViewModels
@using Tickest.Models.Entities
@inject UserManager<Usuario> userManager
@inject Tickest.Data.TickestContext _context

@{
    Layout = "_LayoutGerenciador";
    ViewData["Title"] = "Tickest - Departamentos";

    var user = await userManager.FindByEmailAsync(User.Identity.Name);

    var usuario = _context.Usuarios
        .Where(p => p.Email == User.Identity.Name)
        .FirstOrDefault();

    async Task<bool> Gerenciador()
    {
        return await userManager.IsInRoleAsync(user, "Gerenciador");
    }
    async Task<bool> Responsavel()
    {
        return await userManager.IsInRoleAsync(user, "Responsavel");
    }

    async Task<bool> Cliente()
    {
        return await userManager.IsInRoleAsync(user, "Cliente");
    }
}

<div class="container-fluid" style="background-color: #ffffff; padding: 20px;">
    <h2>Departamentos</h2>
    <p>Departamentos cadastrados no sistema:</p>
    <table class="table table-condensed" id="Tickets">
        <thead>
            <tr>
                @if (await Responsavel() || await Gerenciador())
                {
                    <th>Nome</th>
                    <th>Responsável</th>
                    <th>Edição</th>
                    <th>Deletar</th>
                }
                else
                {
                    <th>Nome</th>
                    <th>Responsável</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var departamento in Model)
            {
                <tr>
                    <td>@departamento.Nome</td>
                    <td>@departamento.Gerenciador</td>
                    @if (await Responsavel())
                    {
                        if (usuario.DepartamentoId == departamento.Id)
                        {
                            <td><a href="@Url.Action("Edit", "Departamentos", new { id = departamento.Id })">Editar</a></td>
                        }
                        else
                        {
                            <td></td>
                        }
                    }
                    else if (await Gerenciador())
                    {
                        <td><a href="@Url.Action("Edit", "Departamentos", new { id = departamento.Id })">Editar</a></td>
                        <td><a href="@Url.Action("Delete", "Departamentos", new { id = departamento.Id })">Deletar</a></td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script>
        $(document).ready(function () {
            $('#Tickets').DataTable({
                "ordering": true,
                "paging": true,
                "searching": true,
                "language": {
                    "emptyTable": "Nenhum registro encontrado na tabela",
                    "info": "Mostrando _START_ até _END_ de _TOTAL_ registros",
                    "infoEmpty": "Mostrando 0 até 0 de 0 Registros",
                    "infoFiltered": "(Filtrado de _MAX_ total registros)",
                    "infoPostFix": "",
                    "thousands": ".",
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "loadingRecords": "Carregando...",
                    "processing": "Processando...",
                    "zeroRecords": "Nenhum registro encontrado",
                    "search": "Pesquisar",
                    "paginate": {
                        "next": "Próximo",
                        "previous": "Anterior",
                        "first": "Primeiro",
                        "last": "Último"
                    },
                    "aria": {
                        "sortAscending": ": Ordenar colunas de forma ascendente",
                        "sortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });
    </script>
}